### ISSUE TITLE
Issue: #1 Text needs to be red.

### ISSUE THREAD

**Issue by Lakorthus** [SchoolOfCode/bc13_w9_project-frontend-l-the-cool-j-s-1#30]
I would like to have the text in the prep interview in red colour and bold!

**Comment by edsoncanganjo** [comment]
Is it for something like this below?

![image](https://user-images.githubusercontent.com/34490218/204938235-90953dbc-5859-4473-82b5-11cf78cdfce7.png)

**Comment by kailoon** [comment]
The title or the body text?

![image](https://user-images.githubusercontent.com/151661/204951114-f7ce0fdc-6dc7-4a91-ae62-e41241d59770.png)

The readability is poor. I'd recommend to use the wheat color in bold.
